# Generated by Django 5.2.6 on 2025-10-01 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Corbeille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_table', models.CharField(max_length=50)),
                ('ID_enregistrement', models.IntegerField()),
                ('date_suppression', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Corbeille',
                'verbose_name_plural': 'Corbeilles',
            },
        ),
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_culture', models.CharField(max_length=50, unique=True)),
                ('variete_culture', models.CharField(blank=True, max_length=50, null=True)),
                ('cycle_culture', models.IntegerField(blank=True, help_text='Durée du cycle en jours', null=True)),
                ('saisonnalite_culture', models.CharField(blank=True, max_length=30, null=True)),
                ('culture_supprime', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Culture',
                'verbose_name_plural': 'Cultures',
            },
        ),
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_parcelle', models.CharField(max_length=50, unique=True)),
                ('superficie_parcelle', models.DecimalField(decimal_places=2, help_text='Superficie en hectare (ha)', max_digits=10)),
                ('type_sol', models.CharField(blank=True, max_length=50, null=True)),
                ('disponible', models.BooleanField(default=True)),
                ('parcelle_supprime', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Parcelle agricole',
                'verbose_name_plural': 'Parcelles agricoles',
            },
        ),
        migrations.CreateModel(
            name='Unite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unite', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Unité de mesure',
                'verbose_name_plural': 'Unités de mesure',
            },
        ),
        migrations.CreateModel(
            name='Plantation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_plantation_terre', models.DateField()),
                ('methode_culture', models.CharField(blank=True, max_length=50, null=True)),
                ('quantite_plantee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plantation_supprime', models.BooleanField(default=False)),
                ('ID_culture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agriculture.culture')),
                ('ID_parcelle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agriculture.parcelle')),
                ('ID_unite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agriculture.unite')),
            ],
            options={
                'verbose_name': 'Plantation',
                'verbose_name_plural': 'Plantations',
            },
        ),
        migrations.CreateModel(
            name='ProfilUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.PositiveSmallIntegerField(choices=[(1, 'Administrateur'), (2, 'Agriculteur / Technicien')], default=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Suivi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_suivi', models.DateField(auto_now_add=True)),
                ('details_suivi', models.TextField(blank=True, max_length=2000, null=True)),
                ('suivi_supprime', models.BooleanField(default=False)),
                ('ID_plantation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agriculture.plantation')),
            ],
            options={
                'verbose_name': 'Suivi de plantation',
                'verbose_name_plural': 'Suivis de plantations',
            },
        ),
    ]
