# Generated by Django 5.2.6 on 2025-10-02 09:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suivi',
            name='date_suivi',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
