# Generated by Django 5.2.6 on 2025-10-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0002_alter_suivi_date_suivi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suivi',
            name='date_suivi',
            field=models.DateField(auto_now_add=True),
        ),
    ]
