# Generated by Django 5.2.6 on 2025-10-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0003_alter_suivi_date_suivi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culture',
            name='saisonnalite_culture',
            field=models.CharField(choices=[('pluvieuse', 'Saison pluvieuse'), ('seche', 'Saison sèche'), ('toute_annee', 'Toute l’année')], default='pluvieuse', max_length=20),
        ),
        migrations.AlterField(
            model_name='parcelle',
            name='type_sol',
            field=models.CharField(choices=[('argileux', 'Argileux'), ('sableux', 'Sableux'), ('limoneux', 'Limoneux'), ('humifère', 'Humifère'), ('calcaire', 'Calcaire')], default='pluvieuse', max_length=20),
            preserve_default=False,
        ),
    ]
