# Generated by Django 6.0.1 on 2026-01-27 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
                ('variete', models.CharField(max_length=50)),
                ('cycle', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Intrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
                ('provenance', models.CharField(blank=True, max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='Localisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localisation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MethodeCulture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('methode', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
                ('superficie', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Saisonnalite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saison', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeIntrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_intrant', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeSol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_sol', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeSuivi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_suivi', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Unite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbr', models.CharField(max_length=10)),
                ('unite', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Plantation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_plantation', models.DateField()),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.culture')),
                ('methode_culture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.methodeculture')),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.parcelle')),
            ],
        ),
        migrations.CreateModel(
            name='ContenirPlantationIntrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_application', models.DateField()),
                ('cout', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('intrant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.intrant')),
                ('plantation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.plantation')),
            ],
        ),
        migrations.AddField(
            model_name='culture',
            name='saisonnalite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.saisonnalite'),
        ),
        migrations.CreateModel(
            name='Terrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
                ('localisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.localisation')),
            ],
        ),
        migrations.AddField(
            model_name='parcelle',
            name='terrain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.terrain'),
        ),
        migrations.AddField(
            model_name='intrant',
            name='type_intrant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.typeintrant'),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='type_sol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.typesol'),
        ),
        migrations.CreateModel(
            name='Suivi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('details', models.TextField()),
                ('plantation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.plantation')),
                ('type_suivi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.typesuivi')),
            ],
        ),
        migrations.CreateModel(
            name='Recolte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recolte', models.DateField()),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plantation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.plantation')),
                ('unite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.unite')),
            ],
        ),
        migrations.AddField(
            model_name='intrant',
            name='unite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.unite'),
        ),
    ]
